[tools]
node = "24.13.1"
go = "1.26.0"
neovim = "latest"
actionlint = "latest"
aws-vault = "latest"
deck = "latest"
fzf = "latest"
gh = "latest"
task = "latest"
golangci-lint = "latest"
lazygit = "latest"
lua-language-server = "latest"
pnpm = "latest"
docker-cli = "latest"
docker-compose = "latest"
tree-sitter = "latest"
apm = "latest"
"npm:ccusage" = "latest"
